// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthInfo
    {
        /// <summary>
        /// Initializes a new instance of the AuthInfo class.
        /// </summary>
        public AuthInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthInfo class.
        /// </summary>
        public AuthInfo(string bearer = default(string), System.DateTime? expires = default(System.DateTime?), Player user = default(Player))
        {
            Bearer = bearer;
            Expires = expires;
            User = user;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bearer")]
        public string Bearer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expires")]
        public System.DateTime? Expires { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public Player User { get; set; }

    }
}
