// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GameRequest
    {
        /// <summary>
        /// Initializes a new instance of the GameRequest class.
        /// </summary>
        public GameRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GameRequest class.
        /// </summary>
        public GameRequest(string id = default(string), Player sender = default(Player), Player recipient = default(Player))
        {
            Id = id;
            Sender = sender;
            Recipient = recipient;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sender")]
        public Player Sender { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipient")]
        public Player Recipient { get; set; }

    }
}
