// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GameRequestList
    {
        /// <summary>
        /// Initializes a new instance of the GameRequestList class.
        /// </summary>
        public GameRequestList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GameRequestList class.
        /// </summary>
        public GameRequestList(IList<GameRequest> incoming = default(IList<GameRequest>), IList<GameRequest> outgoing = default(IList<GameRequest>))
        {
            Incoming = incoming;
            Outgoing = outgoing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "incoming")]
        public IList<GameRequest> Incoming { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "outgoing")]
        public IList<GameRequest> Outgoing { get; set; }

    }
}
