// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MiniGameResult
    {
        /// <summary>
        /// Initializes a new instance of the MiniGameResult class.
        /// </summary>
        public MiniGameResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MiniGameResult class.
        /// </summary>
        public MiniGameResult(bool? isWin = default(bool?), IList<string> correctAnswer = default(IList<string>), IList<IList<Tile>> tiles = default(IList<IList<Tile>>), string nextMovePlayerId = default(string))
        {
            IsWin = isWin;
            CorrectAnswer = correctAnswer;
            Tiles = tiles;
            NextMovePlayerId = nextMovePlayerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isWin")]
        public bool? IsWin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correctAnswer")]
        public IList<string> CorrectAnswer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tiles")]
        public IList<IList<Tile>> Tiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nextMovePlayerId")]
        public string NextMovePlayerId { get; set; }

    }
}
