// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MiniGameInit
    {
        /// <summary>
        /// Initializes a new instance of the MiniGameInit class.
        /// </summary>
        public MiniGameInit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MiniGameInit class.
        /// </summary>
        public MiniGameInit(string tileId = default(string), string categoryId = default(string))
        {
            TileId = tileId;
            CategoryId = categoryId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tileId")]
        public string TileId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public string CategoryId { get; set; }

    }
}
