// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlatformStats
    {
        /// <summary>
        /// Initializes a new instance of the PlatformStats class.
        /// </summary>
        public PlatformStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformStats class.
        /// </summary>
        public PlatformStats(int? numberOfQuestions = default(int?), int? numberOfCategories = default(int?), int? numberOfGamesPlayed = default(int?), int? numberOfContributions = default(int?))
        {
            NumberOfQuestions = numberOfQuestions;
            NumberOfCategories = numberOfCategories;
            NumberOfGamesPlayed = numberOfGamesPlayed;
            NumberOfContributions = numberOfContributions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfQuestions")]
        public int? NumberOfQuestions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfCategories")]
        public int? NumberOfCategories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfGamesPlayed")]
        public int? NumberOfGamesPlayed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfContributions")]
        public int? NumberOfContributions { get; set; }

    }
}
