// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Tile
    {
        /// <summary>
        /// Initializes a new instance of the Tile class.
        /// </summary>
        public Tile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tile class.
        /// </summary>
        public Tile(System.Guid? id = default(System.Guid?), System.Guid? chosenCategoryId = default(System.Guid?), IList<Category> availableCategories = default(IList<Category>), int? difficulty = default(int?), System.Guid? ownerId = default(System.Guid?))
        {
            Id = id;
            ChosenCategoryId = chosenCategoryId;
            AvailableCategories = availableCategories;
            Difficulty = difficulty;
            OwnerId = ownerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chosenCategoryId")]
        public System.Guid? ChosenCategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availableCategories")]
        public IList<Category> AvailableCategories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "difficulty")]
        public int? Difficulty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerId")]
        public System.Guid? OwnerId { get; set; }

    }
}
