// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikidataGame.Backend.Helpers;

namespace WikidataGame.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190618114344_MovedWinnerPropToGameUser")]
    partial class MovedWinnerPropToGameUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("WikidataGame.Backend.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "e9019ee1-0eed-492d-8aa7-feb1974fb265",
                            Title = "Nature"
                        },
                        new
                        {
                            Id = "ddd333f7-ef45-4e13-a2ca-fb4494dce324",
                            Title = "Culture"
                        },
                        new
                        {
                            Id = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            Title = "Geography"
                        },
                        new
                        {
                            Id = "1b9185c0-c46b-4abf-bf82-e464f5116c7d",
                            Title = "Space"
                        },
                        new
                        {
                            Id = "6c22af9b-2f45-413b-995d-7ee6c61674e5",
                            Title = "Natural Sciences"
                        },
                        new
                        {
                            Id = "f9c52d1a-9315-423d-a818-94c1769fffe5",
                            Title = "History"
                        },
                        new
                        {
                            Id = "4941c348-b4c4-43b5-b3d4-85794c68eec4",
                            Title = "Celebrities"
                        },
                        new
                        {
                            Id = "2a388146-e32c-4a08-a246-472eff12849a",
                            Title = "Entertainment"
                        },
                        new
                        {
                            Id = "7f2baca7-cdf4-4e24-855b-c868d9030ba4",
                            Title = "Politics"
                        },
                        new
                        {
                            Id = "3d6c54d3-0fda-4923-a00e-e930640430b3",
                            Title = "Sports"
                        });
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int>("AccessibleTilesCount");

                    b.Property<int>("MapHeight");

                    b.Property<int>("MapWidth");

                    b.Property<int>("MoveCount");

                    b.Property<string>("NextMovePlayerId")
                        .HasMaxLength(36);

                    b.Property<int>("StepsLeftWithinMove");

                    b.HasKey("Id");

                    b.HasIndex("NextMovePlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.GameUser", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(36);

                    b.Property<string>("UserId")
                        .HasMaxLength(36);

                    b.Property<bool>("IsWinner");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUser");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.MiniGame", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("AnswerOptionsString")
                        .IsRequired();

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("CorrectAnswerString")
                        .IsRequired();

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<int>("Status");

                    b.Property<string>("TaskDescription")
                        .IsRequired();

                    b.Property<string>("TileId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TileId");

                    b.ToTable("MiniGames");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Question", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<int>("MiniGameType");

                    b.Property<string>("SparqlQuery")
                        .IsRequired();

                    b.Property<string>("TaskDescription")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = "a4b7c4ba-6acb-4f9a-821b-7a44aa7b6761",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT ?answer ?question WHERE {  
                          ?item wdt:P31 wd:Q5119.
                          ?item wdt:P1376 ?land.
                          ?land wdt:P31 wd:Q6256.
                          OPTIONAL { 
                            ?item rdfs:label ?answer;
                                    filter(lang(?answer) = 'en')
                              ?land rdfs:label ?question;
                                    filter(lang(?question) = 'en').
                          }
                            }
                        ORDER BY MD5(CONCAT(STR(?answer), STR(NOW()))) LIMIT 4",
                            TaskDescription = "What is the name of the capital of {0}?"
                        },
                        new
                        {
                            Id = "aca0f5f7-b000-42fb-b713-f5fe43748761",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT ?answer (COUNT(?item) AS ?question)
                        WHERE 
                        {
                          ?item wdt:P31 wd:Q6256.
                          ?item wdt:P30 ?continent.
                          ?continent wdt:P31 wd:Q5107.
                          OPTIONAL {?continent rdfs:label ?answer ;
                                    filter(lang(?answer) = 'en')
                                          }
                        }
                        GROUP BY ?continent ?answer
                        ORDER BY MD5(CONCAT(STR(?answer), STR(NOW())))
                        LIMIT 4",
                            TaskDescription = "Which continent has {0} countries?"
                        },
                        new
                        {
                            Id = "9a70639b-3447-475a-905a-e866a0c98a1c",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT ?answer ?question
                        WITH {
                          SELECT DISTINCT ?state ?continent ?stateLabel ?continentLabel WHERE {
                            ?state wdt:P31/wdt:P279* wd:Q3624078;
                                 p:P463 ?memberOfStatement.
                            ?memberOfStatement a wikibase:BestRank;
                                               ps:P463 wd:Q1065.
                            MINUS { ?memberOfStatement pq:P582 ?endTime. }
                            MINUS { ?state wdt:P576|wdt:P582 ?end. }
                            ?state p:P30 ?continentStatement.
                          ?continentStatement a wikibase:BestRank;
                                              ps:P30 ?continent.
                            VALUES ?continent { wd:Q49 wd:Q48 wd:Q46 wd:Q18 wd:Q15 } # ohne Ozeanien
                            MINUS { ?continentStatement pq:P582 ?endTime. }
                          } ORDER BY MD5(CONCAT(STR(?state), STR(NOW())))
                        } AS %states
                        WITH {
                          SELECT ?state ?continent WHERE {
                            INCLUDE %states.
                            {
                              SELECT DISTINCT ?continent WHERE {
                                VALUES ?continent { wd:Q49 wd:Q48 wd:Q46 wd:Q18 wd:Q15 } # ohne Ozeanien
                              } ORDER BY MD5(CONCAT(STR(?continent), STR(NOW())))
                              LIMIT 1
                            }
                          }
                        } AS %selectedContinent
                        WITH {
                          SELECT DISTINCT ?state ?continent WHERE {
                            INCLUDE %selectedContinent.
                          }
                          LIMIT 1
                        } AS %threeStates
                        WITH {
                          # dump continent for false answers (needed for sorting)
                          SELECT ?state ?empty WHERE {
                            INCLUDE %states.
                            FILTER NOT EXISTS { INCLUDE %selectedContinent. }
                          }
                          LIMIT 3
                        } AS %oneState
                        WHERE {
                            { INCLUDE %oneState. } UNION
                            { INCLUDE %threeStates. }

                          SERVICE wikibase:label { 
                            bd:serviceParam wikibase:language 'en'.
                            ?state  rdfs:label ?answer.
                            ?continent rdfs:label ?question.
                          }
                        }
                        ORDER BY DESC(?question)",
                            TaskDescription = "Which country is a part of continent {0}?"
                        },
                        new
                        {
                            Id = "46679c4f-ef97-445d-9a70-d95a5337720f",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT DISTINCT ?question ?answer
                        WITH {
                          SELECT DISTINCT (?state as ?country) WHERE {
                            ?state wdt:P31/wdt:P279* wd:Q3624078;
                                   p:P463 ?memberOfStatement.
                            ?memberOfStatement a wikibase:BestRank;
                                                 ps:P463 wd:Q1065.
                            MINUS { ?memberOfStatement pq:P582 ?endTime. }
                            MINUS { ?state wdt:P576|wdt:P582 ?end. }
                          }
                        } AS %states
                        WITH { 
                              SELECT DISTINCT ?country ?sea WHERE {
                                  BIND(wd:Q545 AS ?sea).
                                  ?sea wdt:P205 ?country.
                                }
                            } as %basins
                        WITH { 
                              SELECT DISTINCT ?country ?sea WHERE {
                                  INCLUDE %basins.
                                } ORDER BY MD5(CONCAT(STR(?country), STR(NOW()))) LIMIT 3
                            } as %threeBasins
                        WITH {
                          SELECT DISTINCT ?country ?sea ?noSea
                            WHERE {
                              INCLUDE %states.
                              ?country wdt:P30 wd:Q46.
                              BIND(wd:Q545 as ?noSea).
                            FILTER NOT EXISTS { INCLUDE %basins.}
                          } ORDER BY MD5(CONCAT(STR(?country), STR(NOW()))) LIMIT 1
                        } AS %oneOther
                        WHERE {
                          { INCLUDE %oneOther. } UNION
                          { INCLUDE %threeBasins. }
                          SERVICE wikibase:label { 
                            bd:serviceParam wikibase:language 'en'. 
                            ?country rdfs:label ?answer.
                            ?noSea rdfs:label ?question. 
                          }
                        }
                        order by DESC(?question)",
                            TaskDescription = "Which country is no basin country of the Baltic Sea?"
                        },
                        new
                        {
                            Id = "4f6c477e-7025-44b4-a3b0-f3ebd8902902",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT DISTINCT ?question ?answer
                        WITH {
                          SELECT DISTINCT (?state as ?country) WHERE {
                            ?state wdt:P31/wdt:P279* wd:Q3624078;
                                   p:P463 ?memberOfStatement.
                            ?memberOfStatement a wikibase:BestRank;
                                                 ps:P463 wd:Q1065.
                            MINUS { ?memberOfStatement pq:P582 ?endTime. }
                            MINUS { ?state wdt:P576|wdt:P582 ?end. }
                          }
                        } AS %states
                        WITH { 
                              SELECT DISTINCT ?country ?sea WHERE {
                                  BIND(wd:Q1247 AS ?sea).
                                  {
                                    ?sea wdt:P205 ?country.
                                  }
                                  UNION
                                  {
                                    INCLUDE %states.
                                    ?country wdt:P361 ?region.
                                    VALUES ?region {wd:Q664609 wd:Q166131 wd:Q778 wd:Q93259 wd:Q19386 wd:Q5317255}.
                                  }
                                } ORDER BY MD5(CONCAT(STR(?country), STR(NOW())))
                            } as %basins
                        WITH { 
                            SELECT DISTINCT ?country ?sea
                            WHERE {
                              INCLUDE %basins.
                                } LIMIT 3
                            } as %threeBasins
                        WITH {
                          SELECT DISTINCT ?country ?noSea
                            WHERE {
                              INCLUDE %states.
                              ?country wdt:P361 ?region.
                              BIND(wd:Q1247 as ?noSea).
                              VALUES ?region {wd:Q12585 wd:Q653884}.
                              FILTER NOT EXISTS {?country wdt:P31 wd:Q112099.}
                              FILTER NOT EXISTS {?country wdt:P31 wd:Q13107770.}
                              FILTER NOT EXISTS {?country wdt:P361 wd:Q27611.}
                              FILTER NOT EXISTS {INCLUDE %basins.}
                          } ORDER BY MD5(CONCAT(STR(?country), STR(NOW())))
                          LIMIT 1
                        } AS %oneOther
                        WHERE {
                          { INCLUDE %oneOther. } UNION
                          { INCLUDE %threeBasins. } 
                          SERVICE wikibase:label { 
                            bd:serviceParam wikibase:language 'en'.
                            ?country rdfs:label ?answer.
                            ?noSea rdfs:label ?question.
                          }
                        }
                        order by DESC(?noSea)",
                            TaskDescription = "Which country is no basin country of the {0}?"
                        },
                        new
                        {
                            Id = "a6a470de-9efb-4fde-9388-6eb20f2ff1f4",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT DISTINCT ?question ?answer
                        WITH {
                          SELECT DISTINCT (?state as ?country) WHERE {
                            ?state wdt:P31/wdt:P279* wd:Q3624078;
                                   p:P463 ?memberOfStatement.
                            ?memberOfStatement a wikibase:BestRank;
                                                 ps:P463 wd:Q1065.
                            MINUS { ?memberOfStatement pq:P582 ?endTime. }
                            MINUS { ?state wdt:P576|wdt:P582 ?end. }
                          }
                          ORDER BY MD5(CONCAT(STR(?state), STR(NOW())))
                        } AS %states
                        WITH { 
                              SELECT DISTINCT ?country WHERE {
                                  BIND(wd:Q4918 AS ?sea).
                                  ?sea wdt:P205 ?country.
                                } LIMIT 3
                            } as %threeBasins
                        WITH {
                          SELECT DISTINCT ?country ?noSea
                            WHERE {
                              BIND(wd:Q4918 AS ?noSea).
                              INCLUDE %states.
                              ?country wdt:P361 ?region.
                              VALUES ?region { wd:Q7204 wd:Q984212 wd:Q27449 wd:Q263686 wd:Q50807777 wd:Q27468 wd:Q27381 }.
                              FILTER NOT EXISTS {?country wdt:P31 wd:Q51576574.}
                          } LIMIT 1
                        } AS %oneOther
                        WHERE {
                          { INCLUDE %oneOther. } UNION
                          { INCLUDE %threeBasins. }
                          SERVICE wikibase:label { 
                            bd:serviceParam wikibase:language 'en'.
                            ?country rdfs:label ?answer.
                            ?noSea rdfs:label ?question.
                          }
                        }
                        order by DESC(?noSea)",
                            TaskDescription = "Which country is no basin country of the {0}?"
                        },
                        new
                        {
                            Id = "29fed1d0-d306-4946-8109-63b8aaf0262e",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 2,
                            SparqlQuery = @"SELECT DISTINCT ?answer ?question WHERE {
                        { SELECT DISTINCT ?river ?continent (avg(?length2) as ?length)
                            WHERE
                            {
                              ?river wdt:P31/wdt:P279* wd:Q355304;
                                 wdt:P2043 ?length2;
                                 wdt:P30 ?continent.
                              {
                                SELECT DISTINCT ?continent WHERE {
                                  VALUES ?continent { wd:Q49 wd:Q48 wd:Q46 wd:Q18 wd:Q15  } # ohne Ozeanien
                                } ORDER BY MD5(CONCAT(STR(?continent), STR(NOW()))) LIMIT 1
                               } 
                            }
                            group by ?river ?continent
                        }
                        OPTIONAL {?continent rdfs:label ?question;
                            filter(lang(?question) = 'en')
                            ?river rdfs:label ?answer ;
                            filter(lang(?answer) = 'en')
                        }
                    }
                    order by desc(?length)
                    limit 4",
                            TaskDescription = "What is the longest river in {0}?"
                        },
                        new
                        {
                            Id = "f88a4dc0-8187-43c4-8775-593822bf4af1",
                            CategoryId = "cf3111af-8b18-4c6f-8ee6-115157d54b79",
                            MiniGameType = 1,
                            SparqlQuery = @"SELECT ?question (CONCAT( ?ans, ' (', ?country, ')' ) as ?answer) WHERE {
                      { SELECT DISTINCT (?answer as ?ans) (MAX(?image) as ?question) ?country WHERE { 
                        ?landmark wdt:P31/wdt:P279* wd:Q2319498;
                                 wikibase:sitelinks ?sitelinks;
                                 wdt:P18 ?image;
                                 wdt:P17 ?cntr.
                        ?landmark wdt:P1435 ?type.
                        FILTER(?sitelinks >= 10)

                        SERVICE wikibase:label { 
                            bd:serviceParam wikibase:language 'en'.
                            ?cntr rdfs:label ?country.
                            ?landmark rdfs:label ?answer.}
                        }
                        GROUP BY ?answer ?country
                        ORDER BY MD5(CONCAT(STR(?question), STR(NOW())))
                        LIMIT 4 
                      }
                    }",
                            TaskDescription = "Which famous monument is this: {0}?"
                        });
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Tile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("ChosenCategoryId")
                        .HasMaxLength(36);

                    b.Property<int>("Difficulty");

                    b.Property<string>("GameId");

                    b.Property<bool>("IsAccessible");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.HasIndex("ChosenCategoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("DeviceId")
                        .IsRequired();

                    b.Property<int>("Platform");

                    b.Property<string>("PushChannelUrl");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Game", b =>
                {
                    b.HasOne("WikidataGame.Backend.Models.User", "NextMovePlayer")
                        .WithMany()
                        .HasForeignKey("NextMovePlayerId");
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.GameUser", b =>
                {
                    b.HasOne("WikidataGame.Backend.Models.Game", "Game")
                        .WithMany("GameUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WikidataGame.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.MiniGame", b =>
                {
                    b.HasOne("WikidataGame.Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WikidataGame.Backend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WikidataGame.Backend.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WikidataGame.Backend.Models.Tile", "Tile")
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Question", b =>
                {
                    b.HasOne("WikidataGame.Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WikidataGame.Backend.Models.Tile", b =>
                {
                    b.HasOne("WikidataGame.Backend.Models.Category", "ChosenCategory")
                        .WithMany()
                        .HasForeignKey("ChosenCategoryId");

                    b.HasOne("WikidataGame.Backend.Models.Game")
                        .WithMany("Tiles")
                        .HasForeignKey("GameId");

                    b.HasOne("WikidataGame.Backend.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
