// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WikidataGame.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GameInfo
    {
        /// <summary>
        /// Initializes a new instance of the GameInfo class.
        /// </summary>
        public GameInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GameInfo class.
        /// </summary>
        public GameInfo(string gameId = default(string), bool? isAwaitingOpponentToJoin = default(bool?), string message = default(string))
        {
            GameId = gameId;
            IsAwaitingOpponentToJoin = isAwaitingOpponentToJoin;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gameId")]
        public string GameId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAwaitingOpponentToJoin")]
        public bool? IsAwaitingOpponentToJoin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
